[project]
name = 'Blockchain-Enabled-Shared-Workshop-Access'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.maintenance-fund]
path = 'contracts/maintenance-fund.clar'
clarity_version = 2
epoch = 2.5

[contracts.tool-inventory]
path = 'contracts/tool-inventory.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
